services:
  # Grafana Service
  grafana:
    image: grafana/grafana-oss:10.0.3  # Latest open-source Grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Admin password
    volumes:
      - /mnt/nfs/grafana_data:/var/lib/grafana  # NFS share for Grafana data
    ports:
      - "3000:3000"  # Expose Grafana port
    deploy:
      resources:
        limits:
          memory: 2g  # Limit Grafana to 2GB of RAM
          cpus: '1.0'  # Limit Grafana to 1 CPU core

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /mnt/nfs/prometheus_data:/prometheus  # NFS share for Prometheus data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration file
    ports:
      - "9090:9090"  # Expose Prometheus port
    deploy:
      resources:
        limits:
          memory: 3g  # Limit Prometheus to 3GB of RAM
          cpus: '1.5'  # Limit Prometheus to 1.5 CPU cores

  # Loki Service (Log aggregation)
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - /mnt/nfs/loki_data:/loki  # NFS share for Loki data
      - ./loki-config.yml:/etc/loki/local-config.yaml  # Loki configuration file
    ports:
      - "3100:3100"  # Expose Loki port
    deploy:
      resources:
        limits:
          memory: 3g  # Limit Loki to 3GB of RAM
          cpus: '1.5'  # Limit Loki to 1.5 CPU cores

  # Node Exporter
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"  # Expose Node Exporter port
    deploy:
      resources:
        limits:
          memory: 200m  # Limit Node Exporter to 200MB of RAM
          cpus: '0.2'  # Limit Node Exporter to 0.2 CPU cores
        reservations:
          memory: 100m  # Request 100MB of RAM
          cpus: '0.1'  # Request 0.1 CPU cores

  # cAdvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"  # Expose cAdvisor port
    deploy:
      resources:
        limits:
          memory: 500m  # Limit cAdvisor to 500MB of RAM
          cpus: '0.5'  # Limit cAdvisor to 0.5 CPU cores
        reservations:
          memory: 250m  # Request 250MB of RAM
          cpus: '0.25'  # Request 0.25 CPU cores

  # Tempo Service (Tracing)
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    volumes:
      - /mnt/nfs/tempo_data:/var/lib/tempo
      - ./tempo-config.yml:/etc/tempo/tempo-config.yaml
    ports:
      - "3200:3200"  # Expose Tempo port
    deploy:
      resources:
        limits:
          memory: 2g  # Limit Tempo to 2GB of RAM
          cpus: '1.0'  # Limit Tempo to 1 CPU core
        reservations:
          memory: 1g  # Request 1GB of RAM
          cpus: '0.5'  # Request 0.5 CPU cores

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data: