services:
  # Grafana Service
  grafana:
    image: grafana/grafana-oss:10.0.3
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ${PROMETHEUS_DATA_PATH}:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  # Loki Service (Log aggregation)
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ${LOKI_DATA_PATH}:/loki
      - ./loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    deploy:
      resources:
        limits:
          memory: 3g
          cpus: '2.0'
        reservations:
          memory: 1g
          cpus: '1.0'

  # cAdvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY}:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8150:8080"
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: '0.5'
        reservations:
          memory: 250m
          cpus: '0.25'

  # Tempo Service (Tracing)
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    volumes:
      - ${TEMPO_DATA_PATH}:/var/lib/tempo
      - ./tempo-config.yml:/etc/tempo/tempo-config.yaml
    ports:
      - "3200:3200"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

  ## Open WebUI Service
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui1
    network_mode: "host"
    ports:
      - "3050:8080"
    volumes:
      - ${OPEN_WEBUI_DATA_PATH}:/app/backend/data
    restart: unless-stopped
    environment:
      - VECTOR_DB=qdrant
      - VECTOR_DB_HOST=qdrant
      - VECTOR_DB_PORT=6333
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.50'
          memory: 512M

  # Replace Milvus service with Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${QDRANT_DATA_PATH}:/qdrant/storage
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          memory: 1g
          cpus: '0.5'

# Promtail Service (Log shipping)
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ${PROMTAIL_DATA_PATH}:/var/lib/promtail
      - ./promtail-config.yml:/etc/promtail/promtail-config.yaml
    ports:
      - "3500:3500"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data:
  open-webui:
  qdrant_data: